name: Build & Push to Registry
run-name: Build and push to GitHub Registry (@${{ github.actor }})

on:
  push:
    branches:
      - trunk

jobs:
  build-push:
    name: Build image and push to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 
            - ghcr.io/${{ github.repository_owner }}/bookstack:latest
            - ghcr.io/${{ github.repository_owner }}/bookstack:${{ github.sha }}

